services:
  app:
    image: surfstudent-bot_prod
    build:
      context: .
      target: production
      args:
        - NODE_ENV=production
    working_dir: /app
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]