services:
  app:
    build:
      context: .
      target: development
      args:
        - NODE_ENV=development
    working_dir: /app
    image: surfstudent_bot_dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - dist:/app/dist
      - ./secrets/gcp-key.json:/app/secrets/gcp-key.json:ro
    ports:
      - "8080:8443"
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcp-key.json
    env_file:
      - .env
    command: [ "npm", "run", "dev" ]
volumes:
  node_modules:
  dist:
